loss_hyp:
  use_focal_loss: true # 是否使用focal loss方法计算分类损失
  focal_loss_gamma: 1.5 # focal loss参数
  focal_loss_alpha: 0.25  # focal loss参数
  iou_loss_scale: 0.05  # 回归损失（bbox损失）权重
  cls_loss_scale: 0.5  # 分类损失权重
  cof_loss_scale: 1.0  # 置信度损失权重
  anchor_match_thr: 4.0  # 该参数用于过滤预测框与标签框之间匹配的阈值
  class_smooth_factor: 1.0 # 标签平滑
  cls_pos_weight: 1.0  # 
  cof_pos_weight: 1.0  # 

train_hyp:
  pretrained_model_path: "/home/uih/JYL/Programs/YOLO/jupyter/yolov5s_for_voc.pth"  # 预训练模型路径
  train_img_dir: ~  # 存放训练图像的文件夹路径
  train_lab_dir: ~  # 存放训练label的文件夹路径
  test_img_dir: "./result/coco_test_imgs"  # for test
  val_img_dir: ~  # validation image dir
  val_lab_dir: ~  # validation label dir
  aspect_ratio: false  
  aspect_ratio_path: ~  # 训练时，按照训练集中图片长宽比从小到大的顺序输入到网络，该文件保存的是训练集中所有image的长宽比
  cache_num: 0
  input_img_size:  # 输入训练网络的图片大小
    - 640
    - 640
  batch_size: 4
  drop_last: true  # Pytorch DataLoader中的参数
  pin_memory: false  # Pytorch DataLoader中的参数
  shuffle: true  # Pytorch DataLoader中的参数
  num_workers: 0  # Pytorch DataLoader中的参数
  total_epoch: 300
  device: "gpu"  # 是否使用GPU进行训练['gpu' or 'cpu']
  accumulate_loss_step: 64  # 累积梯度下降
  do_ema: true  # 是否维持一个Everage Moving Model
  validation_every: 0.5  # 每隔多少个epoch validate一次
  show_tbar_every: 5  # 每个多少个step显示实时训练状态信息
  use_tta: true  # validation时是否使用TTA
  log_save_path: ~  
  save_log_txt: true  # 是否保存log文件
  model_save_dir: ~
  mutil_scale_training: false  # 是否使用多尺度训练
  current_work_path: null  # 当前工作目录（可以不设置）
  calculate_map_every: 0.5  # 每个多少个epoch计算一次map
  calculate_map: true
  save_ckpt_every: 1  # 每隔多少个epoch保存一次模型
  model_type: 'small'  # 使用模型类型
  use_auxiliary_classifier: false # 是否使用额外的分类器对预测结果进行调优

optimizer_hyp:
  optimizer: 'sgd' # 优化器类别/['sgd' or 'adam']
  init_lr: 0.01
  weight_decay: 0.0001
  momentum: 0.9
  lr_scheculer_bias: 0.2

warm_up:
  do_warmup: true  # 是否开启预热训练
  warmup_epoch: 3
  warmup_bias_lr: 0.1
  warmup_momentum: 0.8

data_hyp:
  data_aug_scale: 0.5
  data_aug_shear: 0.0
  data_aug_translate: 0.1
  data_aug_degree: 0.0
  data_aug_prespective: 0.0
  data_aug_hsv_p: 1.0
  data_aug_hsv_hgain: 0.015
  data_aug_hsv_sgain: 0.7
  data_aug_hsv_vgain: 0.4
  data_aug_mixup_p: 0.0
  data_aug_fliplr_p: 0.5
  data_aug_flipud_p: 0.0
  data_aug_fill_value: 128
  data_aug_mosaic_p: 1.0
  data_aug_cutout_p: 1.0
  data_aug_cutout_iou_thr: 0.3  # 若随机产生的mask与target任一bbox的iou值大于该阈值，则会采取一些行动避免这种情况发生（默认操作是舍弃该mask）

nms_hyp:
  iou_threshold: 0.2
  conf_threshold: 0.3
  cls_threshold: 0.3
  max_predictions_per_img: 300
  min_prediction_box_wh: 2
  max_prediction_box_wh: 4096
  iou_type: 'iou'
  infer_img_save_path: ~
  mutil_label: false  # 一个object是否可以有多个标签
  agnostic: true  # 是否在同类别的bbox之间进行NMS
  postprocess_bbox: true  # 是否对预测框进行调优
  wfb: false  # use NMS or Weighted Fusion Bbox
  wfb_weights: 
    - 1
    - 1
    - 1
  wfb_iou_threshold: 0.5
  wfb_skip_box_threshold: 0.001

val_hyp:
  save_img: false
  show_gt_bbox: false
  save_pred_bbox: false
  half: false  # 是否使用半精度（float16）进行预测

