loss_hyp:
  use_focal_loss: false
  tar_box_scale_factor: 
    - 0.1
    - 0.1
    - 0.2
    - 0.2
  negative_iou_thr: 0.4
  positive_iou_thr: 0.5
  iou_loss_scale: 0.0
  l1_loss_scale: 1.0
  cls_loss_scale: 1.0
  alpha : 0.25
  gamma : 2.0
    
train_hyp:
  pretrained_model_path : ''
  freeze_bn: false
  train_img_dir: "../../Dataset/COCO/train/img"  # 存放训练图像的文件夹路径
  train_lab_dir: "../../Dataset/COCO/train/lab"  # 存放训练label的文件夹路径
  name_path: "../../Dataset/COCO/train/names.txt"
  test_img_dir: "./result/coco_test_imgs"  # for test
  val_img_dir: "../../Dataset/COCO/val/img"  # validation image dir
  val_lab_dir: "../../Dataset/COCO/val/lab"  # validation label dir 
  aspect_ratio: false  
  aspect_ratio_path: './dataset/pkl/aspect_ratio.pkl'  # 训练时，按照训练集中图片长宽比从小到大的顺序输入到网络，该文件保存的是训练集中所有image的长宽比
  cache_num: 2000000
  input_img_size: 
    - 512
    - 512
  batch_size: 64
  drop_last: true
  pin_memory: true
  shuffle: true
  num_workers: 0
  total_epoch: 300
  device: 'gpu'
  accumulate_loss_step: 64
  do_ema: false
  validation_every: 0.5
  show_tbar_every: 2
  save_log_every: 2
  use_tta : false
  save_ckpt_every: 1  # 每隔多少个epoch保存一次模型
  mutil_scale_training : false
  enable_data_aug: true
  no_data_aug_epoch: 10
  start_epoch: 0
  calculate_map_every : 300
  num_anchors : 9
  resnet_layers : 
    - 3
    - 4
    - 6
    - 3
  iou_type: 'ciou'
  use_auxiliary_classifier: false # 是否使用额外的分类器对预测结果进行调优
  enable_tensorboard: true
  log_identifier: 'retinanet_debug'
  random_seed: 7

warmup_hyp:
  do_warmup: true
  warmup_epoch: 3
  warmup_bias_max_lr: 0.001
  warmup_momentum: 0.9

optimizer_hyp:
  scheduler_type: 'linear'
  optimizer : 'sgd'
  basic_lr_per_img: 0.003125
  weight_decay : 0.00001
  momentum : 0.99
  lr_max_ds_scale: 0.0001

data_hyp:
  data_aug_prespective_p: 1.0
  data_aug_scale: 0.5
  data_aug_shear: 0.0
  data_aug_translate: 0.1
  data_aug_degree: 0.0
  data_aug_prespective: 0.0
  data_aug_hsv_p: 1.0
  data_aug_hsv_hgain: 0.015
  data_aug_hsv_sgain: 0.7
  data_aug_hsv_vgain: 0.4
  data_aug_mixup_p: 0.0
  data_aug_fliplr_p: 0.5
  data_aug_flipud_p: 0.0
  data_aug_fill_value: 128
  data_aug_mosaic_p: 1.0
  data_aug_cutout_p: 1.0
  data_aug_cutout_iou_thr: 0.3
  data_aug_scale_jitting_p: 0.0

nms_hyp:
  iou_threshold: 0.2
  cls_threshold: 0.6
  max_predictions_per_img : 300
  min_prediction_box_wh : 2
  max_prediction_box_wh : 4096
  nms_type : 'iou'
  infer_img_save_path: ~
  mutil_label: false
  agnostic : true
  postprocess_bbox : false
  wfb : false  # use NMS or Weighted Fusion Bbox
  wfb_weights: 
  - 1
  - 1
  - 1
  wfb_iou_threshold: 0.5
  wfb_skip_box_threshold : 0.001

val_hyp:
  save_gt_bbox: false  # 计算map后，是否保存gt
  save_pred_bbox: false  # 计算map后，是否将预测结果保存
  half: false  # 是否使用半精度（float16）进行预测
  compute_metric_conf_threshold: 0.001
  compute_metric_iou_threshold: 0.65
  compute_metric_cls_threshold: 0.001 
