loss_hyp:
  use_focal_loss: true # 是否使用focal loss方法计算分类损失
  focal_loss_gamma: 1.5 # focal loss参数
  focal_loss_alpha: 0.25  # focal loss参数
  iou_loss_scale: 0.05  # 回归损失（bbox损失）权重
  cls_loss_scale: 0.5  # 分类损失权重
  cof_loss_scale: 1.0  # 置信度损失权重
  anchor_match_thr: 4.0  # 该参数用于过滤预测框与标签框之间匹配的阈值
  class_smooth_factor: 1.0 # 标签平滑
  cls_pos_weight: 1.0  # 
  cof_pos_weight: 1.0  # 

train_hyp:
  pretrained_model_path: ""  # 预训练模型路径
  train_img_dir: "../../Dataset/COCO/train/img"  # 存放训练图像的文件夹路径
  train_lab_dir: "../../Dataset/COCO/train/lab"  # 存放训练label的文件夹路径
  name_path: "../../Dataset/COCO/train/names.txt"
  test_img_dir: "./result/coco_test_imgs"  # for test
  val_img_dir: "../../Dataset/COCO/val/img"  # validation image dir
  val_lab_dir: "../../Dataset/COCO/val/lab"  # validation label dir
  aspect_ratio: false  
  enable_data_aug: true
  aspect_ratio_path: './dataset/pkl/aspect_ratio.pkl'  # 训练时，按照训练集中图片长宽比从小到大的顺序输入到网络，该文件保存的是训练集中所有image的长宽比
  cache_num: 200000
  input_img_size:  # 输入训练网络的图片大小
    - 512
    - 512
  batch_size: 24
  drop_last: true  # DataLoader
  pin_memory: True  # DataLoader
  random_seed: 7
  shuffle: true  # DataLoader
  num_workers: 0  # DataLoader
  start_epoch: 0
  total_epoch: 300
  device: "gpu"  # 是否使用GPU进行训练['gpu' or 'cpu']
  accumulate_loss_step: 48  # 累积梯度下降
  do_ema: true
  validation_every: 1  # 每隔多少个epoch validate一次
  use_tta: true  # validation时是否使用TTA
  mutil_scale_training: false 
  calculate_map_every: 299  # 每个多少个epoch计算一次map
  save_ckpt_every: 1  # 每隔多少个epoch保存一次模型
  model_type: 'small'
  use_auxiliary_classifier: false 
  enable_tensorboard: true
  log_identifier: 'debug'
  save_log_every: 2
  no_data_aug_epoch: 10

optimizer_hyp:
  scheduler_type: 'linear'
  optimizer: 'sgd' # 优化器类别/['sgd' or 'adam']
  basic_lr_per_img: 0.00625
  weight_decay: 0.0001
  momentum: 0.9
  lr_max_ds_scale: 0.001

warm_up:
  do_warmup: true  # 是否开启预热训练
  warmup_epoch: 3
  warmup_bias_max_lr: 0.1  # warmup 期间bias部分参数可以取到的最大lr(warmup_bias_max_lr >= hyp['lr'])
  warmup_momentum: 0.8

data_hyp:
  data_aug_prespective_p: 1.0
  data_aug_scale: 0.5
  data_aug_shear: 0.0
  data_aug_translate: 0.1
  data_aug_degree: 0.0
  data_aug_prespective: 0.0005  # should not big
  data_aug_hsv_p: 1.0
  data_aug_hsv_hgain: 0.015
  data_aug_hsv_sgain: 0.7
  data_aug_hsv_vgain: 0.4
  data_aug_mixup_p: 0.3
  data_aug_fliplr_p: 0.3
  data_aug_flipud_p: 0.0
  data_aug_fill_value: 114
  data_aug_mosaic_p: 1.0
  data_aug_cutout_p: 0.1
  data_aug_cutout_iou_thr: 0.5  # 若随机产生的mask与target任一bbox的iou值大于该阈值，则会采取一些行动避免这种情况发生（默认操作是舍弃该mask）
  data_aug_scale_jitting_p: 0.0

nms_hyp:
  iou_threshold: 0.2
  conf_threshold: 0.3
  cls_threshold: 0.3
  max_predictions_per_img: 300
  min_prediction_box_wh: 2
  max_prediction_box_wh: 4096
  iou_type: 'iou'
  infer_img_save_path: ~
  mutil_label: false  # 一个object是否可以有多个标签
  agnostic: true  # 是否在同类别的bbox之间进行NMS
  postprocess_bbox: true  # 是否对预测框进行调优
  wfb: false  # use NMS or Weighted Fusion Bbox
  wfb_weights: 
    - 1
    - 1
    - 1
  wfb_iou_threshold: 0.5
  wfb_skip_box_threshold: 0.001

val_hyp:
  save_gt_bbox: false  # 计算map后，是否保存gt
  save_pred_bbox: false  # 计算map后，是否将预测结果保存
  half: false  # 是否使用半精度（float16）进行预测

